/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-09-04 07:18:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bookreviewform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1752455263419L));
    _jspx_dependants.put("jar:file:/C:/2025_spring_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/daye_archive/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Book Review</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("    background-color: #f7f7f7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("    flex: 1;\r\n");
      out.write("    min-height: 400px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-card {\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    box-shadow: 0 6px 18px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    padding: 30px 40px;\r\n");
      out.write("    max-width: 1000px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-bottom: 25px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-bottom: 6px;\r\n");
      out.write("    color: #444;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], textarea, select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("    resize: vertical;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-group {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    transition: background-color 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-submit {\r\n");
      out.write("    background-color: #f5f5f5;\r\n");
      out.write("    color: black;\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-submit:hover {\r\n");
      out.write("    background-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-cancel {\r\n");
      out.write("    background-color: #f5f5f5;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-cancel:hover {\r\n");
      out.write("    background-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write(".search-results {\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("}\r\n");
      out.write(".search-item {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background 0.2s;\r\n");
      out.write("}\r\n");
      out.write(".search-item:hover {\r\n");
      out.write("    background: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write(".search-item img {\r\n");
      out.write("    width: 50px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function searchBook() {\r\n");
      out.write("    let keyword = document.getElementById(\"searchKeyword\").value;\r\n");
      out.write("    fetch(\"/book/search?keyword=\" + encodeURIComponent(keyword))\r\n");
      out.write("        .then(res => res.json())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("            let resultsDiv = document.getElementById(\"searchResults\");\r\n");
      out.write("            resultsDiv.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("            data.forEach(book => {\r\n");
      out.write("                let div = document.createElement(\"div\");\r\n");
      out.write("                div.classList.add(\"book-item\");\r\n");
      out.write("\r\n");
      out.write("                // 🔹 백틱 대신 문자열 결합\r\n");
      out.write("                let imgTag = '<img src=\"' + book.thumbnail + '\" width=\"50\">';\r\n");
      out.write("                let titleSpan = '<span>' + book.title + ' (' + book.authors + ')</span>';\r\n");
      out.write("                div.innerHTML = imgTag + titleSpan;\r\n");
      out.write("\r\n");
      out.write("                div.onclick = function() {\r\n");
      out.write("                    let selectedDiv = document.getElementById(\"selectedBook\");\r\n");
      out.write("                    selectedDiv.innerHTML = '<img src=\"' + book.thumbnail + '\" width=\"80\"><br>' +\r\n");
      out.write("                                            book.title + ' - ' + book.authors;\r\n");
      out.write("\r\n");
      out.write("                    document.getElementById(\"bookTitle\").value = book.title;\r\n");
      out.write("                    document.getElementById(\"bookAuthors\").value = book.authors;\r\n");
      out.write("                    document.getElementById(\"bookThumbnail\").value = book.thumbnail;\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                resultsDiv.appendChild(div);\r\n");
      out.write("            });\r\n");
      out.write("        })\r\n");
      out.write("        .catch(err => console.error(err));\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navi.jsp", out, false);
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mainprofile.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-card\">\r\n");
      out.write("            <h2>📚 책 리뷰 작성</h2>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"title\">제목</label>\r\n");
      out.write("                    <input type=\"text\" id=\"title\" name=\"title\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- 책 검색 영역 -->\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"book\">책 검색</label>\r\n");
      out.write("                    <input type=\"text\" id=\"searchKeyword\" placeholder=\"책 제목 검색\">\r\n");
      out.write("                    <button type=\"button\" onclick=\"searchBook()\">검색</button>\r\n");
      out.write("                    <div id=\"searchResults\" class=\"search-results\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 선택된 책 정보 표시 -->\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>선택된 책</label>\r\n");
      out.write("                    <div id=\"selectedBook\">선택된 책이 없습니다.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- hidden input (DB 저장용) -->\r\n");
      out.write("                <input type=\"hidden\" id=\"bookTitle\" name=\"bookTitle\">\r\n");
      out.write("                <input type=\"hidden\" id=\"bookAuthors\" name=\"bookAuthors\">\r\n");
      out.write("                <input type=\"hidden\" id=\"bookThumbnail\" name=\"bookThumbnail\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"content\">내용</label>\r\n");
      out.write("                    <textarea id=\"content\" name=\"content\" rows=\"8\" required></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"hashtags\">해시태그</label>\r\n");
      out.write("                    <input type=\"text\" id=\"hashtags\" name=\"hashtags\" placeholder=\"#독서 #감상\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"btn-group\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-submit\">작성하기</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-cancel\" onclick=\"history.back()\">취소</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/bookreviewform.jsp(175,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/book/insert");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
